export const stakingAbi = [
  {
    inputs: [
      { internalType: "contract IOAYC", name: "OAYC_", type: "address" },
      { internalType: "contract IMOAYC", name: "MOAYC_", type: "address" },
      { internalType: "contract IERC20", name: "token_", type: "address" },
      { internalType: "address", name: "owner_", type: "address" },
      { internalType: "uint256", name: "rewardRate_", type: "uint256" },
      { internalType: "uint256", name: "pairMulti_", type: "uint256" },
      { internalType: "uint256", name: "notPairMulti_", type: "uint256" },
      { internalType: "uint256", name: "oneOneMulti_", type: "uint256" },
      {
        internalType: "uint256[]",
        name: "availablePeriods_",
        type: "uint256[]",
      },
      { internalType: "uint256[]", name: "oayc1x1_", type: "uint256[]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "MOAYC",
    outputs: [{ internalType: "contract IMOAYC", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OAYC",
    outputs: [{ internalType: "contract IOAYC", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newAvailablePeriod", type: "uint256" },
    ],
    name: "addAvailablePeriods",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newTokenId", type: "uint256" }],
    name: "addOayc1x1",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_oaycIds", type: "uint256[]" },
      { internalType: "uint256[]", name: "_moaycIds", type: "uint256[]" },
    ],
    name: "calculateTokens",
    outputs: [{ internalType: "uint256", name: "counter", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_oaycIds", type: "uint256[]" },
      { internalType: "uint256[]", name: "_moaycIds", type: "uint256[]" },
      { internalType: "address", name: "_sender", type: "address" },
    ],
    name: "checkOwner",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimAllRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_index", type: "uint256" }],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "flipStarted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getAllPositionsInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "accruedReward", type: "uint256" },
          { internalType: "uint256", name: "maximumReward", type: "uint256" },
          { internalType: "uint256", name: "stakedPeriod", type: "uint256" },
          { internalType: "uint256", name: "remainingPeriod", type: "uint256" },
          { internalType: "bool", name: "positionKind", type: "bool" },
          {
            internalType: "uint256[]",
            name: "arrayIdsOayc",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "arrayIdsMoayc",
            type: "uint256[]",
          },
          { internalType: "string[]", name: "oaycTokenURIs", type: "string[]" },
          {
            internalType: "string[]",
            name: "moaycTokenURIs",
            type: "string[]",
          },
        ],
        internalType: "struct Staking.PositionInfo[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_index", type: "uint256" },
    ],
    name: "getMaximumRewardPerPosition",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "getPositionInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "accruedReward", type: "uint256" },
          { internalType: "uint256", name: "maximumReward", type: "uint256" },
          { internalType: "uint256", name: "stakedPeriod", type: "uint256" },
          { internalType: "uint256", name: "remainingPeriod", type: "uint256" },
          { internalType: "bool", name: "positionKind", type: "bool" },
          {
            internalType: "uint256[]",
            name: "arrayIdsOayc",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "arrayIdsMoayc",
            type: "uint256[]",
          },
          { internalType: "string[]", name: "oaycTokenURIs", type: "string[]" },
          {
            internalType: "string[]",
            name: "moaycTokenURIs",
            type: "string[]",
          },
        ],
        internalType: "struct Staking.PositionInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_owner", type: "address" }],
    name: "getPositionsByOwner",
    outputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "startTimestamp", type: "uint256" },
          { internalType: "uint256", name: "endTimestamp", type: "uint256" },
          { internalType: "uint256", name: "tokens", type: "uint256" },
          { internalType: "bool", name: "positionKind", type: "bool" },
          {
            internalType: "uint256[]",
            name: "arrayIdsOayc",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "arrayIdsMoayc",
            type: "uint256[]",
          },
        ],
        internalType: "struct Staking.Position[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_index", type: "uint256" },
    ],
    name: "getRewardAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_index", type: "uint256" },
    ],
    name: "getStakingPertiod",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_index", type: "uint256" },
    ],
    name: "isActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isStarted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_oaycIds", type: "uint256[]" },
      { internalType: "uint256[]", name: "_moaycIds", type: "uint256[]" },
      { internalType: "uint256", name: "_periodIndex", type: "uint256" },
    ],
    name: "lock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
    name: "moaycRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "notPairMulti",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oneOneMulti",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pairMulti",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "positions",
    outputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "startTimestamp", type: "uint256" },
      { internalType: "uint256", name: "endTimestamp", type: "uint256" },
      { internalType: "uint256", name: "tokens", type: "uint256" },
      { internalType: "bool", name: "positionKind", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_userAddress", type: "address" },
    ],
    name: "positionsOf",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardRate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_availablePeriods",
        type: "uint256[]",
      },
    ],
    name: "setAvailablePeriods",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newMulti", type: "uint256" }],
    name: "setNotPairMulti",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newMulti", type: "uint256" }],
    name: "setOneOnOneMulti",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newOwner", type: "address" }],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newMulti", type: "uint256" }],
    name: "setPairMulti",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newRewardRate", type: "uint256" },
    ],
    name: "setRewardRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_oaycIds", type: "uint256[]" },
      { internalType: "uint256[]", name: "_moaycIds", type: "uint256[]" },
      { internalType: "uint256", name: "_periodIndex", type: "uint256" },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_oaycIds", type: "uint256[]" },
      { internalType: "uint256[]", name: "_moaycIds", type: "uint256[]" },
    ],
    name: "transferPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userPositionsAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];
